### ISSUE TITLE
Make the calendar a week template

### ISSUE THREAD

**Issue by TusharAgey** [OpenKatta/UniTimetable#13]
Current calendar shows day-wise timetable. So tweak the calendar so that it will show the week template. Like: -
![template](https://cloud.githubusercontent.com/assets/14837532/23542169/b050fc58-0011-11e7-9bcf-47b098998baf.png)

**Comment by abhisheklolage** [comment]
We are not doing this, are we?

**Comment by TusharAgey** [comment]
nope... That's why I have closed this issue!.🙂
